version: "3.8"
services:
  # image micro-email
  micro_email:
    build:
      args:
        - user=fhariano
        - uid=1000
      context: ./
      dockerfile: dockerfile
    image: laravel-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    depends_on:
      - redis_micro_email
      - queue
    networks:
      - microemail
  
  # nginx
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 8005:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - microemail

  # queue micro email
  queue:
    build:
      args:
        - user=fhariano
        - uid=1000
      context: ./
      dockerfile: dockerfile
    restart: unless-stopped
    working_dir: /var/www/
    command: "php artisan queue:work"
    volumes:
      - ./:/var/www
    networks:
      - microemail

  # redis
  redis_micro_email:
    image: redis:latest
    networks:
      - microemail

networks:
  microemail:
    driver: bridge